In [1]:
import numpy as np

np.__version__

'1.26.4'

In [4]:
a = np.full((2,3), [1,2,3])
a

array([[1, 2, 3],
       [1, 2, 3]])

In [5]:
b = np.full((3,2), [2,3])
b

array([[2, 3],
       [2, 3],
       [2, 3]])

In [6]:
import numpy as np

a = np.arange(3)
a

array([0, 1, 2])

In [7]:
print(a +2)
print(a - 2)
print(a * 2)
print(a / 2)

[2 3 4]
[-2 -1  0]
[0 2 4]
[0.  0.5 1. ]


In [8]:
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
b = np.full_like(a, [1,2,3])
b

array([[1, 2, 3],
       [1, 2, 3]])

In [10]:
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[[2 4 6]
 [5 7 9]]
[[0 0 0]
 [3 3 3]]
[[ 1  4  9]
 [ 4 10 18]]
[[1.  1.  1. ]
 [4.  2.5 2. ]]


In [11]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [12]:
b = np.arange(0.5, 4, 1)
b

array([0.5, 1.5, 2.5, 3.5])

In [13]:
a += b

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

In [14]:
b +=a 
b

array([0.5, 2.5, 4.5, 6.5])

In [15]:
a @ b

31.0

In [16]:
a.dot(b)

31.0

In [17]:
b.dot(a)

31.0

In [18]:
a = np.array([[10,20], [5,8], [1,2]])
a

array([[10, 20],
       [ 5,  8],
       [ 1,  2]])

In [19]:
a.sum()

46

In [20]:
a.sum(axis=0)

array([16, 30])

In [21]:
a.sum(axis=1)

array([30, 13,  3])

In [22]:
import numpy as np

print(np.sum(a))
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))

46
[16 30]
[30 13  3]


In [23]:
a = np.array([[3,5,8], [1,2,3]])
a

array([[3, 5, 8],
       [1, 2, 3]])

In [24]:
a.cumsum()

array([ 3,  8, 16, 17, 19, 22])

In [25]:
a.cumsum(axis=0)

array([[ 3,  5,  8],
       [ 4,  7, 11]])

In [26]:
a.cumsum(axis=1)

array([[ 3,  8, 16],
       [ 1,  3,  6]])

In [27]:
import numpy as np
a = np.array([1,4,9])
np.sqrt(a)

array([1., 2., 3.])

In [28]:
np.log(a)

array([0.        , 1.38629436, 2.19722458])

In [29]:
import numpy as np
a = np.array([1,4,9])
a

array([1, 4, 9])

In [30]:
b = np.full_like(a, 2)
b

array([2, 2, 2])

In [31]:
np.add(a,b)

array([ 3,  6, 11])

In [32]:
np.divide(a,b)

array([0.5, 2. , 4.5])

In [33]:
np.power(a,b)

array([ 1, 16, 81])