In [1]:
from numpy import array

a = array([3,4,5])
b = array([8,7,6])
a+b

array([11, 11, 11])

In [2]:
from numpy import array

a = array([3,4,5,7])
b = array([8,7,6])
a * b

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [3]:
from numpy import array

a= array([3,4,5])
a

array([3, 4, 5])

In [4]:
b = 2
b

2

In [5]:
a + b

array([5, 6, 7])

In [6]:
from numpy import array

A = array([[1,2,3], [1,2,3]])
A

array([[1, 2, 3],
       [1, 2, 3]])

In [7]:
A + 2

array([[3, 4, 5],
       [3, 4, 5]])

In [9]:
from numpy import arange

x = arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
y = arange(-1, 2)
y

array([-1,  0,  1])

In [11]:
x*y

array([[-1,  0,  3],
       [-4,  0,  6],
       [-7,  0,  9]])

In [12]:
x + y

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [13]:
from numpy import arange
x = arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
y = arange(3,10,3).reshape(3,1)
y

array([[3],
       [6],
       [9]])

In [15]:
x / y

array([[0.33333333, 0.66666667, 1.        ],
       [0.66666667, 0.83333333, 1.        ],
       [0.77777778, 0.88888889, 1.        ]])

In [16]:
x - y

array([[-2, -1,  0],
       [-2, -1,  0],
       [-2, -1,  0]])

In [18]:
from numpy import arange

x = arange(1,4)
x


array([1, 2, 3])

In [19]:
y = arange(1,4).reshape(3,1)
y

array([[1],
       [2],
       [3]])

In [20]:
x *y

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [21]:
x - y

array([[ 0,  1,  2],
       [-1,  0,  1],
       [-2, -1,  0]])

In [22]:
from numpy import arange

x = arange(0, 10, 3).reshape(4,1)
x

array([[0],
       [3],
       [6],
       [9]])

In [24]:
y = arange(1,3)
y

array([1, 2])

In [25]:
x * y

array([[ 0,  0],
       [ 3,  6],
       [ 6, 12],
       [ 9, 18]])

In [26]:
x + y

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

In [27]:
from numpy import array

x = array([0, 10 , 20, 30])
x

array([ 0, 10, 20, 30])

In [29]:
a = x[None, :]
a

array([[ 0, 10, 20, 30]])

In [33]:
import numpy as np

a = x[np.newaxis, :]
a

array([[ 0, 10, 20, 30]])

In [34]:
a = x[:, np.newaxis]
a

array([[ 0],
       [10],
       [20],
       [30]])

In [35]:
from numpy import array

b = array([1,2,3])
b

array([1, 2, 3])

In [36]:
a + b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [38]:
a * b

array([[ 0,  0,  0],
       [10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

3-7 고급색인

In [1]:
import numpy as np

x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
print(x[1])
print(x[:5])

1
[0 1 2 3 4]


In [3]:
print(x[[2]])
print(x[[2,3]])

[2]
[2 3]


In [4]:
x[[2,3,5,8]]

array([2, 3, 5, 8])

In [5]:
x[np.array([5,3,-4,8])]

array([5, 3, 6, 8])

In [6]:
x[np.array([10])]

IndexError: index 10 is out of bounds for axis 0 with size 10

In [7]:
from numpy import arange

x = arange(56).reshape(7, 8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [8]:
x[0, 1]

1

In [9]:
x[:, 2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [10]:
x[[0], [1]]

array([1])

In [11]:
x[:, [5,4]]

array([[ 5,  4],
       [13, 12],
       [21, 20],
       [29, 28],
       [37, 36],
       [45, 44],
       [53, 52]])

In [12]:
x[[1,3]]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [13]:
x[[1,3], :]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [14]:
x[[1,3], [2,2]]

array([10, 26])

In [15]:
x[[1,3],[2]]

array([10, 26])

In [16]:
x[[1,3], [3,3]]

array([11, 27])

In [17]:
x[[1,3],[3]]

array([11, 27])

In [18]:
from numpy import array

x[array([0,2,4]), array([0, 1])]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [19]:
x[np.array([0,2,4]),1]

array([ 1, 17, 33])

In [20]:
print(x[0, 1])
print(x[2,1])
print(x[4,1])

1
17
33


In [21]:
from numpy import arange
a = arange(40).reshape(5,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [22]:
a[2:4, 3:7]

array([[19, 20, 21, 22],
       [27, 28, 29, 30]])

In [23]:
a[arange(2,4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [24]:
a[arange(2,4)][:, [1, 0]]

array([[17, 16],
       [25, 24]])

In [25]:
a[arange(2,5)][:, [1,0,3,5]]

array([[17, 16, 19, 21],
       [25, 24, 27, 29],
       [33, 32, 35, 37]])

In [26]:
a[arange(2,5)][:, [-1,-8,-1]]

array([[23, 16, 23],
       [31, 24, 31],
       [39, 32, 39]])

4.1

In [27]:
import numpy as  np

a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [28]:
b = np.arange(6,12).reshape(3,2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [29]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [30]:
c = np.arange(20, 24).reshape(2,2)
c

array([[20, 21],
       [22, 23]])

In [31]:
np.vstack((a,c))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [20, 21],
       [22, 23]])

In [32]:
np.vstack((a,b,c))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [20, 21],
       [22, 23]])

In [33]:
d = np.array([100,200])
np.vstack((a,d))

array([[  0,   1],
       [  2,   3],
       [  4,   5],
       [100, 200]])

In [34]:
d = np.array([100,200,300])
np.vstack((a,d))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

In [35]:
import numpy as np
x = np.array([1,2,3])
y = np.array([5,6,7])
np.vstack((x,y))

array([[1, 2, 3],
       [5, 6, 7]])

In [36]:
import numpy as np
a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [37]:
b = np.arange(10, 19).reshape(3,3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [38]:
np.hstack((a,b))

array([[ 0,  1, 10, 11, 12],
       [ 2,  3, 13, 14, 15],
       [ 4,  5, 16, 17, 18]])

In [39]:
c = np.array([[10, 20], [30, 40]])
c

array([[10, 20],
       [30, 40]])

In [40]:
np.hstack((a,c))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

In [41]:
import  numpy as np

a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [42]:
b = np.arange(10,22).reshape(3,4)

In [43]:
np.hstack((a,b))

array([[ 0,  1, 10, 11, 12, 13],
       [ 2,  3, 14, 15, 16, 17],
       [ 4,  5, 18, 19, 20, 21]])

In [44]:
x = np.array([1,2,3])
y = np.array([10,20,30])
np.column_stack((x,y))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [45]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [46]:
y[:, np.newaxis]

array([[10],
       [20],
       [30]])

In [47]:
x = np.array([1,2,3])
y = np.array([10,20,30])
np.column_stack((x[:, np.newaxis], y[:, np.newaxis]))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [48]:
np.hstack((x,y))

array([ 1,  2,  3, 10, 20, 30])

In [49]:
np.column_stack == np.hstack

False

In [50]:
import numpy as np
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [52]:
b = np.arange(10, 22).reshape(4,3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [53]:
np.row_stack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [54]:
np.vstack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [55]:
a = np.array([4.,2.,1])
b = np.array([3.,8., 7.])
print(np.row_stack((a,b)))

[[4. 2. 1.]
 [3. 8. 7.]]


In [56]:
print(np.vstack((a,b)))

[[4. 2. 1.]
 [3. 8. 7.]]


In [57]:
np.row_stack == np.vstack

True

In [60]:
import numpy as np
a = np.array([1,2])
b = np.array([3,4])
c = np.array([5,6])

In [61]:
np.concatenate((a,b,c))

array([1, 2, 3, 4, 5, 6])

In [62]:
np.concatenate((a,b,c) , axis=0)

array([1, 2, 3, 4, 5, 6])

In [63]:
np.concatenate((a,b,c), axis= None)

array([1, 2, 3, 4, 5, 6])

In [64]:
import numpy as np
x= np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [65]:
y = np.arange(10, 16).reshape(2,3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [66]:
z = np.arange(20, 24).reshape(2,2)
z

array([[20, 21],
       [22, 23]])

In [67]:
np.concatenate((x,y))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15]])

In [68]:
np.concatenate((x,y,z"))

SyntaxError: unterminated string literal (detected at line 1) (648210607.py, line 1)

In [69]:
np.concatenate((x,y), axis=1)

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15]])

In [70]:
np.concatenate((x,y,z), axis=1)

array([[ 0,  1,  2, 10, 11, 12, 20, 21],
       [ 3,  4,  5, 13, 14, 15, 22, 23]])

In [71]:
np.concatenate((x,y), axis=None)

array([ 0,  1,  2,  3,  4,  5, 10, 11, 12, 13, 14, 15])

In [72]:
import numpy as np

a = np.array([1,2,3])
a

array([1, 2, 3])

In [73]:
b = np.array([4,5,6])
b

array([4, 5, 6])

In [74]:
np.stack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
np.stack((a,b), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [76]:
np.stack((a,b), axis=-1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [77]:
x = np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [78]:
y = np.arange(10,16).reshape(2,3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [79]:
z = np.arange(20,26).reshape(2, 3)
z

array([[20, 21, 22],
       [23, 24, 25]])

In [81]:
ax0 = np.stack((x,y,z), axis = 0)
ax0

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[10, 11, 12],
        [13, 14, 15]],

       [[20, 21, 22],
        [23, 24, 25]]])

In [82]:
ax0.shape

(3, 2, 3)

In [83]:
ax1 = np.stack((x,y,z), axis=1)
ax1

array([[[ 0,  1,  2],
        [10, 11, 12],
        [20, 21, 22]],

       [[ 3,  4,  5],
        [13, 14, 15],
        [23, 24, 25]]])

In [84]:
ax0.shape

(3, 2, 3)

In [85]:
ax2 = np.stack((x,y,z), axis=2)
ax2

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

In [86]:
ax0.shape

(3, 2, 3)

In [87]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [88]:
x[:,:, np.newaxis]

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [89]:
np.expand_dims(x, axis=2)

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [90]:
y

array([[10, 11, 12],
       [13, 14, 15]])

In [91]:
y[:, :, np.newaxis]

array([[[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

In [92]:
z

array([[20, 21, 22],
       [23, 24, 25]])

In [93]:
np.expand_dims(z, axis=2)

array([[[20],
        [21],
        [22]],

       [[23],
        [24],
        [25]]])

In [94]:
np.stack((x,y,z), axis=2)

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

In [95]:
import numpy as np
a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [96]:
c = np.arange(1, 6,2)
c

array([1, 3, 5])

In [97]:
c[:, np.newaxis]

array([[1],
       [3],
       [5]])

In [98]:
np.hstack((a, c[:, np.newaxis]))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [99]:
np.hstack((a,c))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [100]:
np.hstack((a, np.expand_dims(c, axis=1)))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [101]:
np.column_stack((a,c))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [102]:
import numpy as np
a = np.arange(1, 13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [103]:
b = np.arange(1, 5)
b

array([1, 2, 3, 4])

In [104]:
np.row_stack((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [105]:
np.vstack((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [106]:
import numpy as np
a = np.array([1,2,3])
b= np.array([4,5,6])

np.c_[a,b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [107]:
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [113]:
x = np.array([[1,2,3]])
y= np.array([[4,5,6]])

In [114]:
np.c_[x,y]

array([[1, 2, 3, 4, 5, 6]])

In [115]:
np.column_stack((x,y))

array([[1, 2, 3, 4, 5, 6]])

In [116]:
np.c_[x, 10 ,20 ,y]

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [120]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])

In [121]:
np.r_[a,b]

array([1, 2, 3, 4, 5, 6])

In [122]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [123]:
np.row_stack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [124]:
np.row_stack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [126]:
np.r_[a, 0, 0, b]

array([1, 2, 3, 0, 0, 4, 5, 6])

In [127]:
np.r_[3:10:3, [0]*2, 5, 6]

array([3, 6, 9, 0, 0, 5, 6])

In [128]:
np.r_[-1:1:6j, [0]*2, 5, 6]

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ,  0. ,  0. ,  5. ,  6. ])

In [129]:
np.linspace(-1, 1, 6)

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ])

In [130]:
a = np.array([[0, 1, 2], [3,4,5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [131]:
np.r_[a,a,a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [132]:
np.r_['0', a, a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [133]:
np.r_['-1',a , a]

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [134]:
np.r_['1', a, a]

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [135]:
np.r_['0, 2', [1,2,3], [4,5,6]]

array([[1, 2, 3],
       [4, 5, 6]])

In [136]:
np.r_['0, 3', [1,2,3], [4,5,6]]

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [137]:
np.r_['0, 3, 0', [1,2,3], [4,5,6]]

array([[[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[6]]])

In [138]:
np.r_['0,3,0', [1,2,3], [4,5,6]].shape

(6, 1, 1)

In [139]:
np.r_['0, 3, 1', [1,2,3], [4,5,6]]

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [140]:
np.r_['0, 3, 1', [1,2,3], [4,5,6]].shape

(2, 3, 1)

In [141]:
np.r_['0, 3, 2', [1,2,3], [4,5,6]]

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [143]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a.shape)
print(b.shape)

(3,)
(3,)


In [144]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [145]:
np.r_[a,b]

array([1, 2, 3, 4, 5, 6])

In [146]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

In [147]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [148]:
np.row_stack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [149]:
np.r_[a[np.newaxis, :], b[np.newaxis, :]]

array([[1, 2, 3],
       [4, 5, 6]])

In [150]:
np.concatenate((a[np.newaxis, :], b[np.newaxis, :]))

array([[1, 2, 3],
       [4, 5, 6]])

In [151]:
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [153]:
np.hstack((a[:, np.newaxis], b[:, np.newaxis]))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [156]:
np.concatenate(((a[:, np.newaxis], b[:, np.newaxis])), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])